version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestScaffChangesProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/TestScaffChangesProject
  gitUsername: PoojaAnandGit
  gitBranch: main
